name: Déploiment Site internet

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Déploiement

    steps:
      - uses: actions/checkout@v2
      - name: Déploiement FTP
        uses: sand4rt/ftp-deployer@v1.3
        with:
          host: ftp.galinettes-bouvines.fr
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # The local folder location
          local_folder: website
